/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionContainer: typeof import('./components/Operations/Action/ActionContainer.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    BuyMeCoffee: typeof import('./components/BuyMeCoffee.vue')['default']
    ClassificationPreview: typeof import('./components/ClassificationPreview.vue')['default']
    DialogueInterface: typeof import('./components/DialogueInterface.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Faq: typeof import('./components/Faq.vue')['default']
    FileFilter: typeof import('./components/Operations/Filter/FileFilter.vue')['default']
    FileFilterSelector: typeof import('./components/Operations/Filter/FileFilterSelector.vue')['default']
    FileOrganizer: typeof import('./components/FileOrganizer.vue')['default']
    FileOrganizerColumnView: typeof import('./components/FileOrganizerColumnView.vue')['default']
    FilesTable: typeof import('./components/Operations/TableView/FilesTable.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HandlerContainer: typeof import('./components/Operations/Handlers/HandlerContainer.vue')['default']
    HandlerMenu: typeof import('./components/HandlerMenu.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    Operations: typeof import('./components/Operations/Operations.vue')['default']
    OperationWrapper: typeof import('./components/Operations/OperationWrapper.vue')['default']
    PluginLoadError: typeof import('./components/Utils/PluginLoadError.vue')['default']
    PluginLoading: typeof import('./components/Utils/PluginLoading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./components/Upload.vue')['default']
  }
}
